### ISSUE TITLE
App crashing on certain versions of Android

### ISSUE THREAD

**Issue by o355** [ValXp/IFWatcher#2]
So on some versions of android...namely 4.0 ICS (CM 9), and on an Android 5.1 emulator, the app crashes the second I click on a server. Any way to get this fixed?

**Comment by ValXp** [comment]
This crash happens when the Google Play Services are not installed or are out of date.
On the emulator you will need to create an emulator with a system image with Google APIs to enable access to the Google Play services.
On the CM9 rom you might want to check if you have an update available on Google Play Store for the Google Play Services.

On the next release of the app there will be an error dialog instead of a crash.
The Google Play Services are needed for the app to be able to display the map.

**Comment by o355** [comment]
Good to know...always wondering why it was crashing. I'll see if on CM 9 I can get a GPS update going.

**Comment by ValXp** [comment]
Fixed: https://github.com/ValXp/IFWatcher/commit/b59571ea811705b56fe234ae65a88f0f2959eb94
